import { Inter } from "next/font/google";
import { MenuProvider } from "@/context/MenuContext";
import "./styles/globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Andresninop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MenuProvider>
        <body className={inter.className}>
          <NavBar />
          {children}
          <Footer />
        </body>
      </MenuProvider>
    </html>
  );
}
