import Head from "next/head";
import styles from "./styles/index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Andresninop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.andres}>
        <h1>My Work</h1>
        <p>PATINANDO TODOS LOS MARDITOS DIAS</p>
        <iframe
          width="640"
          height="360"
          src="https://www.youtube.com/embed/ZCdWpndXhLg"
          title="portafolio"
          frameborder="0"
          allowfullscreen
        ></iframe>
      </main>
    </>
  );
}
